### ISSUE TITLE
Does not work properly on iOS

### ISSUE THREAD

**Issue by Carlosps** [ghenry22/cordova-plugin-music-controls2#10]
I have tried some solutions to make it work on iOS, but none of them seem to work.

The weird part is that it did work a few times after I left the audio playing in my application. Now I am unable to make it work.

Does anyone have any idea about how to solve this?

**Comment by ghenry22** [comment]
I have this working in multiple apps under ios without any issue currently.

One thing to note, you should use the cordova-plugin-media if you want to use this plugin.  If you are using HTML5 audio or video it overrides the remote controls metadata on iOS.

Make sure that you have background audio capability enabled for your app, otherwise it won't be able to play music in the background.

Double check the path to the cover image if you're using one, it needs to be a native path as this plugin runs in the native space, this can differ to what you would use in the webview.

Also note that the iOS emulator behaviour is a bit hit and miss with remote controls.  You really need to test on a real device to check the behaviour.  You can do a debug build with a phone attached over USB so that you can still debug what is going on, as long as you are running on a real device.

**Comment by netmikey** [comment]
@ghenry22 have you tried using it with the [`WKWebView` engine](https://github.com/apache/cordova-plugin-wkwebview-engine)? The plugin doesn't seem to work at all when using that engine.

** Edit: it seems that the above only holds true for html5 audio. I modified the app to use cordova-plugin-media and the controls seem to work.

**Comment by ekelokorpi** [comment]
@ghenry22 could you give an example for the native path of the cover image? Can't get it to work. Thanks!

**Comment by ghenry22** [comment]
It works fine with wkwebview, the problem as you have noted is using HTML5 audio.  Unfortunately when you use HTML5 audio the audio element just overrides the remote controls on iOS.  I haven't been able to find a way around this while still using HTML5 audio.

Using the native media plugin will make it all play nice as you have mentioned and is the way to go currently.
