### ISSUE TITLE
Android - Stuck notification

### ISSUE THREAD

**Issue by JumBay** [ghenry22/cordova-plugin-music-controls2#20]
Hi,

Some of my users reported that sometimes the notification cannot be removed from the notification center while nothing is playing. The only way to remove it is by killing the app. I've also experienced this on a Pixel 4 with Android 10. 
I've updated the app to display the close button on the notification but it has no effect when this happens, otherwise the button works.

I don't have much information.

Do you have any idea what could do this?

Thanks

**Comment by ghenry22** [comment]
Make sure you have dismissable : true set when you create the controls, then the user can just swipe the notification away any time they want.

Also if playback stops (ie reaches the end of the playlist or whatever), you might want to call the destroy method here and it will destroy the notification as nothing is playing any more.

Otherwise the notification should be destroyed when the app is killed.

I'll do some testing with the close button to see what might be stopping it from dismissing in some situations as well, as that should always work.
