### ISSUE TITLE
Pause icon won't change

### ISSUE THREAD

**Issue by julianCast** [ghenry22/cordova-plugin-music-controls2#39]
I've not installed the background mode, and I'm using native media plugin as you recommended. 

I'm waiting for the event **running** to create controls, but then if I pause the music, the notification icon wont change.
```
    this.music = this.media.create(trackSrc)
      this.music.onStatusUpdate.subscribe(
        (status) => {
          switch (status) {
              case this.media.MEDIA_STARTING:
              break;
              case this.media.MEDIA_RUNNING:
                this.loadMusicControls() // LOAD MUSIC CONTROLS
              break;
          }}
       )
      this.music.play()
```
And this is how I create the controls:
```
loadMusicControls()
  {
    MusicControls.destroy()

    // Music Controls
    MusicControls.create({
      track       : this.currentlyPlaying().title,	
      artist      : this.currentlyPlaying().author,					
      cover       : this.bookCover,	
    
      // hide previous/next/close buttons:
      hasPrev   : false,		// show previous button, optional, default: true
      hasNext   : false,		// show next button, optional, default: true
      hasPause   : true,		// show pause button, optional, default: false
      hasClose  : true,		// show close button, optional, default: false
    }, (s) =>{},  (error) =>{});
    
    function eventsReader(playListService, action) {
       ...
    }

    MusicControls.subscribe((events) => {eventsReader(this, events)});

    // Start listening for events
    // The plugin will run the events function each time an event is fired
    MusicControls.listen();

  }
```

**Comment by AntonERG** [comment]
I have the same issue, a workaround that works for me is to add following code wherever you hit play or pause button (both in the app and on the lock screen controls).
Every time I hit **play**, I add:
```
MusicControls.updateIsPlaying(true);
MusicControls.updateDismissable(false);
```
Every time I hit **pause**, I add:
```
MusicControls.updateIsPlaying(false);
MusicControls.updateDismissable(true);
```

When the user of my app come to the screen with audio, I use following code to initialize music controls:
```
      window.MusicControls.create(
        me.musicControlsConfig,
        () => {
          window.MusicControls.updateIsPlaying(false)
          window.MusicControls.updateDismissable(true)

          function events(action) {
            const message = JSON.parse(action).message
            switch (message) {
              case 'music-controls-next':
                // Do something
                me.next()
                break
              case 'music-controls-previous':
                // Do something
                me.prev()
                break
              case 'music-controls-pause':
                // Do something
                window.MusicControls.updateIsPlaying(false);
                window.MusicControls.updateDismissable(true);
                me.pause(me.my_media)
                break
              case 'music-controls-play':
                // Do something 
                window.MusicControls.updateIsPlaying(true);
                window.MusicControls.updateDismissable(false);
                me.play(me.my_media)
                break
              case 'music-controls-destroy':
                // Do something
                me.stop()
                break
            }
          }

          window.MusicControls.subscribe(events)
          window.MusicControls.listen()

          console.log(
            'music controls created:\n' + JSON.stringify(window.MusicControls)
          )
        },
        (e) => {
          console.log(
            'fail to create music controls, err: ' + JSON.stringify(e)
          )
        }
      )
```

**Comment by julianCast** [comment]
@AEiosApp  Thanks! That's actually the workaround I'm using but I read the author mentioning that should be automatic while using cordova media plugin.

**Comment by ghenry22** [comment]
changing whether the controls are dismissable is entirely up to your preference, whether they are dismissable or not is not tied in any way to the media state, it's up to your app to decide.  Personally I give people the choice if they want to dismiss the notification that's fine.

For the isPlaying status, I have just doublechecked one of my own apps.  What I have done is in the mediacontrols creation bound isPlaying to a variable.  Native media events will update this for system generated changes, like end of track etc and for manual intervention (user pressed button, remote controls event etc) I will update this in my play/pause functions.  This is in angular which has change detection.

Having the update to a variable in your play/pause function let's you only add that code once and have it work regardless of what triggers the change in status.

So you are right it does need to be updated, I just completely missed it due to the way I have always implemented this in my own code, apologies for any confusion there.
