### ISSUE TITLE
Is it too much to ask, an example? something simple, please =(

### ISSUE THREAD

**Issue by mike0liveira** [ghenry22/cordova-plugin-music-controls2#45]
I mean, I've been trying to make the plugin work in my app for a few days, but I'm new to the field. And i'm trying to do something simple but unsuccessful.

please someone tell me where i am wrog...

this is my code:

```
<body>
<audio id="player" controls>
        <source src="music.mp3" type="audio/mp3">
</audio>

<script src="cordova.js"></script>

<script type="text/javascript">

var audioplayer = document.getElementById("player");

MusicControls.create({
  track     : 'name of track',   
  artist     : 'name o artist',          
  album   : 'name of album',   
  cover    : 'albums/album.jpg',
  playIcon: 'media_play',
  pauseIcon: 'media_pause',
  prevIcon: 'media_prev',
  nextIcon: 'media_next',
  closeIcon: 'media_close',
  notificationIcon: 'notification'
}, onSuccess, onError);

</script>
</body>
```

how should i proceed from here? 

I'm having the error: Uncaught ReferenceError: MusicControls is not defined

Should I insert something in config.xml?

how do i reference the plugin to the music? something like: audioplayer.MusicControls.create({ ... }) ??

**Comment by f18nfz** [comment]
Make sure you create the functions onSuccess and onError - that could be the cause of your error message :)
You don't need to insert anything into config.xml - if you added the plugin using the instructed command line all thats all done automatically

**Comment by alexhorner** [comment]
@mike0liveira Could my new issue be related to yours maybe? https://github.com/ghenry22/cordova-plugin-music-controls2/issues/49

**Comment by ghenry22** [comment]
Your error is because MusicControls is not defined.  You would need to use window.MusicControls.  Or check out the ionic-native project for a nice little wrapper that makes it easier to work with.

Also note that you are using HTML5 audio, this will always override the music controls with the basic URL from the browser.  You really need to use the native audio plugin with music controls.

You also need to be waiting for device.ready to fire, it looks like you have just dropped this into an empty HTML file?  Try out something like an Ionic blank starter project to get a base to work from that takes care of a lot of this for you.

**Comment by givethanks1** [comment]
I think you may need the following:

```
function onSuccess() {
        MusicControls.updateIsPlaying(true);
        console.log('success creating controls'); 

  //  code to handle player button events - see main page for examples
      function events(action) {
        const message = JSON.parse(action).message;
	      switch(message) {
		      case 'music-controls-pause':
			      // Do something
			      break;
		      case 'music-controls-play':
			      // Do something
			      break;
	      }
      }
        MusicControls.subscribe(events);
        MusicControls.listen();
}
```

**Comment by almacaw** [comment]
It would be great to include this in the documentation for us non-programmer programmers!
